# Generated by Django 5.0.1 on 2024-02-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_botsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='personal_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CompletedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_services_as_client', to='reservation.person')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_services_as_specialist', to='reservation.person')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.service')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField()),
                ('prepayment_made', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits_as_client', to='reservation.person')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.service')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_as_specialist', to='reservation.person')),
            ],
        ),
    ]
