# Generated by Django 5.0.1 on 2024-02-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_service_person_iban_person_personal_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_start_time', models.TimeField()),
                ('break_duration', models.DurationField()),
                ('work_days', models.CharField(default='1111111', help_text='Binary representation (1 for work day, 0 for day off)', max_length=7)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.person')),
            ],
        ),
    ]
