# Generated by Django 5.0.1 on 2024-02-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedservice',
            name='duration',
            field=models.DurationField(default='00:30:00'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='break_duration',
            field=models.DurationField(default='01:00:00'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='break_start_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='work_days',
            field=models.CharField(default='1111111', help_text='დღეების ორობითი წარმოდგენა (1 სამუშაო დღე, 0 დასვენების დღე)', max_length=7),
        ),
    ]
